on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="/home/runner/work/_temp/keystore"
          mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}/keystore.jks"
          ls -l "${TMP_KEYSTORE_FILE_PATH}" # Debug: Verify keystore file exists
      # Clean the project to ensure a fresh build

      - name: build prod
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_FILE: ${{ runner.temp }}/keystore/keystore.jks

      # Upload the signed APK
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: app/build/outputs/